### ISSUE TITLE
Maximum deposit count

### ISSUE THREAD

**Issue by daejunpark** [ethereum/deposit_contract#26]
## What was wrong?

The current contract does not work as expected if the deposit count becomes `2** DEPOSIT_CONTRACT_TREE_DEPTH`.  (Note that a Merkle tree of height `DEPOSIT_CONTRACT_TREE_DEPTH` should be able to contain `2** DEPOSIT_CONTRACT_TREE_DEPTH` leaf items.)

Here is a problematic scenario.

Suppose `deposit` is called when the current `self.deposit_count` is `2** DEPOSIT_CONTRACT_TREE_DEPTH - 1`.

Then, after the following loop, `i` becomes  `DEPOSIT_CONTRACT_TREE_DEPTH`, since `index + 1` is `2** DEPOSIT_CONTRACT_TREE_DEPTH` and thus the `if` condition is always true for all loop iterations.

https://github.com/ethereum/deposit_contract/blob/600281c0b871837011998cacc12e476d24a23762/deposit_contract/contracts/validator_registration.v.py#L79-L83

Thus, the following assignment leads to the index out of bounds error:

https://github.com/ethereum/deposit_contract/blob/600281c0b871837011998cacc12e476d24a23762/deposit_contract/contracts/validator_registration.v.py#L91

(BTW, the computed `value` is correct even in this case, which is the root of the fully filled Merkle tree.)

**NOTE**:

The index out of bounds error itself can be avoided by increasing the size of `self.branch`,  but in that case, note that `get_deposit_root` will return a wrong value (i.e., `sha3(...sha3(sha3(0,0),sha3(0,0))...)`) when `self.deposit_count` becomes `2** DEPOSIT_CONTRACT_TREE_DEPTH`.

## How can it be fixed?

It is non-trivial to fix (without increasing the gas cost) the contract to be able to receive `2**DEPOSIT_CONTRACT_TREE_DEPTH` deposits, due to the current algorithm of `get_deposit_root`.

Thus, if it is OK to restrict the maximum deposit count to `2**DEPOSIT_CONTRACT_TREE_DEPTH - 1` instead of `2**DEPOSIT_CONTRACT_TREE_DEPTH`, then adding the following assert at the beginning of `deposit` will be a quick solution:
```
assert deposit_count < MAX_DEPOSIT_COUNT
```
where:
```
MAX_DEPOSIT_COUNT: constant(uint256) = 4294967295 # 2**DEPOSIT_CONTRACT_TREE_DEPTH - 1
```

**Comment by yzhang90** [comment]
Another possible fix is: increase size of `branch` to DEPOSIT_CONTRACT_TREE_DEPTH + 1 and when size becomes `2** DEPOSIT_CONTRACT_TREE_DEPTH`, `get_deposit_root` just return branch[DEPOSIT_CONTRACT_TREE_DEPTH]

**Comment by djrtwo** [comment]
After discussing with @daejunpark today, we decided that it makes sense to just put the `assert deposit_count < MAX_DEPOSIT_COUNT` to ensure that the tree doesn't hit this edge case. To note, reaching this point with the constants as currently defined is impossible do to the uni-directional nature of transfers from eth1 to eth2 and the total ether supply (< 130M).

@NIC619 Can you handle this edit?
