### ISSUE TITLE
Redundant assignment in `__init__`

### ISSUE THREAD

**Issue by daejunpark** [ethereum/deposit_contract#27]
## What was wrong?

The following assignment in `__init__` is redundant:

https://github.com/ethereum/deposit_contract/blob/600281c0b871837011998cacc12e476d24a23762/deposit_contract/contracts/validator_registration.v.py#L22

It will result in the unnecessary gas cost (> 31 * gas cost of fresh `SSTORE`) when creating the contract.

**Comment by djrtwo** [comment]
Chatted with @daejunpark, and agree we should remove this line.
@daejunpark also has a proof of equivalence between the incremental and full merkle alg that shows this is unnecessary.

@NIC619 Can you remove this line (and ensure that our tests still pass :joy:)
