### ISSUE TITLE
Loop fusion optimization

### ISSUE THREAD

**Issue by daejunpark** [ethereum/deposit_contract#28]
Logically, the following two loops:

https://github.com/ethereum/deposit_contract/blob/600281c0b871837011998cacc12e476d24a23762/deposit_contract/contracts/validator_registration.v.py#L76-L91

can be combined into the following single loop, which is equivalent but more efficient:

```python
    # add deposit to merkle tree
    i: int128 = 0
    power_of_two: uint256 = 2
    value: bytes32 = sha3(deposit_data)
    for _ in range(DEPOSIT_CONTRACT_TREE_DEPTH):
        if (index+1) % power_of_two != 0:
            break
        i += 1
        power_of_two *= 2
        value = sha3(concat(self.branch[j], value))
    self.branch[i] = value
```

**Comment by djrtwo** [comment]
I agree that we can do this.
I'm a bit torn on whether this effects readability. What do you think @hwwhww @NIC619 ?

**Comment by NIC619** [comment]
I would be in favor of #38 and leaving the two loops as is. The gas saving seems marginal(~100 gas for one iteration in the for-loop) and even in the most exceptional case it saves at most ~3100 gas.

**Comment by djrtwo** [comment]
okay, agreed @NIC619. Let's do #38

**Comment by hwwhww** [comment]
@daejunpark @djrtwo @NIC619 
Should we close this issue?

**Comment by NIC619** [comment]
Yes!
