### ISSUE TITLE
Using `hash_tree_root` for `DepositData`

### ISSUE THREAD

**Issue by hwwhww** [ethereum/deposit_contract#29]
## What was wrong?

Implement https://github.com/ethereum/eth2.0-specs/pull/924 related changes

## How can it be fixed?
1. Update `deposit` APIs to: `def deposit(pubkey: bytes[48], withdrawal_credentials: bytes[32], amount: bytes[8], signature: bytes[96])`
2. Implement `hash_tree_root` of `DepositData` in contract
3. Add tests for it

**Comment by NIC619** [comment]
Should we also incorporate the data length check as suggested in https://github.com/ethereum/eth2.0-specs/issues/710#issuecomment-484295465 into this?

**Comment by djrtwo** [comment]
I think we'll need to still assert length checks on all of these bytes types _or_ ensure that we pad them out. Length checks is probably safer for user.

I don't think we need to include "amount" explicitly anymore as it can be dynamically built and hashed into the tree hash

**Comment by hwwhww** [comment]
@djrtwo 

> I think we'll need to still assert length checks on all of these bytes types or ensure that we pad them out. Length checks is probably safer for user.
> I don't think we need to include "amount" explicitly anymore as it can be dynamically built and hashed into the tree hash

If we remove the `amount` field, I think the only field we need to do length check is exactly the little-endian-encoded `amount`.

@daejunpark hello! And, and thought/consideration about it? :)
