### ISSUE TITLE
Check for the value unit in deposit function

### ISSUE THREAD

**Issue by tsudmi** [ethereum/deposit_contract#33]
Hi,

Currently, the `deposit` function converts deposited value to Gwei ([line](https://github.com/ethereum/deposit_contract/blob/01ca2fbe808b57811247be2b164b1aec6d1ec7fa/deposit_contract/contracts/validator_registration.v.py#L81))

```
deposit_amount: uint256 = msg.value / as_wei_value(1, "gwei")
```
It means that if the `msg.value` is `1.0000000009 ether`,
the `deposit_amount` will be rounded up to `1 ether`. Will it make sense to check that the deposit value is not smaller than Gwei?
```
assert msg.value % as_wei_value(1, "gwei") == 0
```

**Comment by ralexstokes** [comment]
hi @tsudmi !

i think it makes sense to add a note in the specs [https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_deposit-contract.md](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_deposit-contract.md) perhaps that deposit amounts change in increments of `gwei` (so if you send over an eth but less than a gwei increment over 1 eth then you'll burn some wei) but don't see a need to alter the deposit contract (primarily to avoid the additional gas cost involved to ensure this invariant)

**Comment by hwwhww** [comment]
Closing this issue since I think @ralexstokes has answered the concern well. :)
