### ISSUE TITLE
A refactoring suggestion for the loop of `deposit`

### ISSUE THREAD

**Issue by daejunpark** [ethereum/deposit_contract#38]
A refactoring suggestion.

From:
https://github.com/ethereum/deposit_contract/blob/05c3b6ece41871d00535283b8c4bf752fa557f9e/deposit_contract/contracts/validator_registration.v.py#L75-L82

To:
```python
    # add deposit to merkle tree
    i: int128 = 0
    size: uint256 = index + 1
    for _ in range(DEPOSIT_CONTRACT_TREE_DEPTH):
        if bitwise_and(size, 1) == 1:
            break
        i += 1
        size /= 2
```

Benefits:
- Saving gas a bit, i.e., `bitwise_and` instead of `+` and `%`.
- Improving the readability, as it is better aligned with the similar loop of the `get_deposit_root` function:
https://github.com/ethereum/deposit_contract/blob/05c3b6ece41871d00535283b8c4bf752fa557f9e/deposit_contract/contracts/validator_registration.v.py#L52-L58

**Comment by daejunpark** [comment]
@djrtwo this is the refactoring suggestion we discussed.

**Comment by djrtwo** [comment]
Let's bring this in @NIC619
