### ISSUE TITLE
`get_deposit_root` calculates the root value incorrectly for even leaf cases

### ISSUE THREAD

**Issue by dangerousfood** [ethereum/deposit_contract#44]
_If this is a bug report, please fill in the following sections.
If this is a feature request, delete and describe what you would like with examples._

## What was wrong?

https://github.com/ethereum/deposit_contract/blob/ed9c81dd6788142d22106df93d5654578063eb32/deposit_contract/contracts/validator_registration.v.py#L51-L62

in line 51 the root value to be hashed into the tree is assumed to be `0x0000000000000000000000000000000000000000000000000000000000000000` which is correct in the presence of an odd number of leaves.

In the presence of an even number of leaves the root value should be that of the last leaf, prior too it's insertion into the `branch[]`

### Expected Result
adding a parameter to `get_deposit_root`
```
def get_deposit_root(leaf: bytes32) -> bytes32:
    root: bytes32 = leaf
    size: uint256 = self.deposit_count
    for h in range(DEPOSIT_CONTRACT_TREE_DEPTH):
        if bitwise_and(size, 1) == 1:
            root = sha256(concat(self.branch[h], root))
        else:
            root = sha256(concat(root, self.zerohashes[h]))
        size /= 2
    return root
```
additionally adding a check in `deposit` before leaf insertion
```
def deposit(pubkey: bytes[PUBKEY_LENGTH],
            withdrawal_credentials: bytes[WITHDRAWAL_CREDENTIALS_LENGTH],
            signature: bytes[SIGNATURE_LENGTH]):
    # Prevent edge case in computing `self.branch` when `self.deposit_count == MAX_DEPOSIT_COUNT`
    # NOTE: reaching this point with the constants as currently defined is impossible due to the
    # uni-directional nature of transfers from eth1 to eth2 and the total ether supply (< 130M).
    assert self.deposit_count < MAX_DEPOSIT_COUNT

    assert len(pubkey) == PUBKEY_LENGTH
    assert len(withdrawal_credentials) == WITHDRAWAL_CREDENTIALS_LENGTH
    assert len(signature) == SIGNATURE_LENGTH

    deposit_amount: uint256 = msg.value / as_wei_value(1, "gwei")
    assert deposit_amount >= MIN_DEPOSIT_AMOUNT
    amount: bytes[8] = self.to_little_endian_64(deposit_amount)

    index: uint256 = self.deposit_count

    # add deposit to merkle tree
    i: int128 = 0
    size: uint256 = index + 1
    for _ in range(DEPOSIT_CONTRACT_TREE_DEPTH):
        if bitwise_and(size, 1) == 1:
            break
        i += 1
        size /= 2

    zero_bytes_32: bytes32
    pubkey_root: bytes32 = sha256(concat(pubkey, slice(zero_bytes_32, start=0, len=16)))
    signature_root: bytes32 = sha256(concat(
        sha256(slice(signature, start=0, len=64)),
        sha256(concat(slice(signature, start=64, len=32), zero_bytes_32))
    ))
    value: bytes32 = sha256(concat(
        sha256(concat(pubkey_root, withdrawal_credentials)),
        sha256(concat(
            amount,
            slice(zero_bytes_32, start=0, len=24),
            signature_root,
        ))
    ))
    new_deposit_root: bytes32
    leaf: bytes32 = value
    if self.full_deposit_count == CHAIN_START_FULL_DEPOSIT_THRESHOLD:
       if !get_deposit_count()+1%2 == 0:
          leaf = 0x0000000000000000000000000000000000000000000000000000000000000000
      else:
         new_deposit_root = self.get_deposit_root(leaf)

    for j in range(DEPOSIT_CONTRACT_TREE_DEPTH):
        if j < i:
            value = sha256(concat(self.branch[j], value))
        else:
            break
    self.branch[i] = value

    self.deposit_count += 1
    log.Deposit(
        pubkey,
        withdrawal_credentials,
        amount,
        signature,
        self.to_little_endian_64(index),
    )

    if deposit_amount >= FULL_DEPOSIT_AMOUNT:
        self.full_deposit_count += 1
        if self.full_deposit_count == CHAIN_START_FULL_DEPOSIT_THRESHOLD:
            timestamp_day_boundary: uint256 = (
                as_unitless_number(block.timestamp) -
                as_unitless_number(block.timestamp) % SECONDS_PER_DAY +
                2 * SECONDS_PER_DAY
            )
            if new_deposit_root != 0x0000000000000000000000000000000000000000000000000000000000000000:
               new_deposit_root: bytes32 = self.get_deposit_root(leaf)
            log.Eth2Genesis(new_deposit_root,
                            self.to_little_endian_64(self.deposit_count),
                            self.to_little_endian_64(timestamp_day_boundary))
            self.chainStarted = True
```
## How can it be fixed?

I submitted a suggested code fix above but I did not thoroughly vet the implementation

**Comment by ralexstokes** [comment]
i reviewed the existing code and don't see a problem. it is _very_ non-obvious what is going on as the contract only stores the rightmost-branch of the tree at any given time. `get_deposit_root` can then construct the the correct root based on the current deposit count and the data stored in `branch` (mixing in `zerohashes` as required). on top of this, we have a test here that suggests the contract is ok: 

https://github.com/ethereum/deposit_contract/blob/dev/tests/contracts/test_deposit.py#L171-L200

i would suggest taking another pass at the contract state each time a new deposit is added, noting that what gets stored in `branch` are the right-most non-zero (or hashes thereof) elements of the current tree. this strategy is taken to reduce gas costs which we want in general to lower the barrier to entry for anyone to be a validator :)

is this is satisfactory then we can close the issue -- if you still see a problem, could you give a test case that fails? (or explain why the tests we have are broken)

**Comment by daejunpark** [comment]
Here is our formal correctness proof of `get_deposit_root` under the contract invariant (see Lemma 9):
https://github.com/runtimeverification/verified-smart-contracts/blob/master/deposit/formal-incremental-merkle-tree-algorithm.pdf

This proof is not fully mechanized, and thus may have human errors, but I hope it can help you to clarify your issue, or find an error in our proof.

**Comment by yulidai** [comment]
Why do I always think the logic is reversed? Which should be:
```python
for h in range(DEPOSIT_CONTRACT_TREE_DEPTH):
    if bitwise_and(size, 1) == 0:
        root = sha256(concat(self.branch[h], root))
    else:
        root = sha256(concat(root, self.zerohashes[h]))
    size /= 2
```

It confuses me, maybe I have to read the code carefully again

**Comment by daejunpark** [comment]
@yulidai Yes, it is a bit confusing at first sight. (Indeed, this confusingness led to [a bug](https://github.com/ethereum/deposit_contract/issues/26) which is now fixed.) The thing is that this loop traverses the path from the `size`-th leaf (where the 0th leaf being the leftmost one) to the root --- note that leaves are filled up-to `(size - 1)`-th node, and the `size`-th leaf is empty. (See [this paper](https://daejunpark.github.io/deposit.pdf), especially Lemma 9, for more details.)  This seemingly "off-by-one" traverse allows us to avoid handling extra cases, which saves gas --- please find that your suggested code doesn't work when `size` is 0 or an odd number.
